export const Routes =  {
    Home: 'HomeScreen',
    Onboard: 'OnboardingScreen',
    SignupFlow1: 'SignupFlow1',
    SignupFlow2: 'SignupFlow2',
    SignupFlow3: 'SignupFlow3',
    SignupFlow4: 'SignupFlow4',
    Prompt: 'OnboardingPromptsScreen',
    Welcome: 'WelcomeScreen',
    LoginFlow1: 'LoginFlow1Screen',
    RegistrationFlow: 'RegistrationFlow',
    LoginFlow: 'LoginFlow',
    MainNavigation: 'MainNavigation',
    AuthNavigation: 'AuthNavigation',
    Search: 'SearchScreen',
    Profile: 'ProfileScreen',
    Progress: 'ProgressScreen',
    Activity: 'ActivityScreen',
    Main: 'MainHomeScreen',
    Notify: 'NotificationScreen',
    Articles: 'ArticleScreen',
    WorkoutTracker: 'WorkoutTrackerScreen',
    WorkoutDetailA: 'WorkoutDetailFlow1Screen',
    WorkoutDetailB: 'WorkoutDetailFlow2Screen',
    WorkoutSchedule: 'WorkoutScheduleScreen',
    AddSchedule: 'AddScheduleScreen'
}